from enum import Enum

class GlassType(Enum):
    BUILDING_WINDOWS_FLOAT_PROCESSED = 1
    BUILDING_WINDOWS_NON_FLOAT_PROCESSED = 2
    VEHICLE_WINDOWS_FLOAT_PROCESSED = 3
    VEHICLE_WINDOWS_NON_FLOAT_PROCESSED = 4
    CONTAINERS = 5
    TABLEWARE = 6
    HEADLAMPS = 7